trigger:
- main
- jw-prototype-deploy-test

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '22.x'

stages:
- stage: BuildTest
  displayName: 'Build and Test'
  jobs:  
    - job: 
      steps:
      - task: UseNode@1
        inputs:
          version: $(nodeVersion)
          displayName: 'Install Node.js'

      - script: |
         npm install
        displayName: 'Install dependencies'

      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: |
            src/**
            public/**
          targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy project files'

      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: 'nodejs-app'
          targetPath: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Publish pipeline artifact'

- stage: Deploy
  displayName: 'Deploy'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
    - job:
      steps:
      - task: AzureRmWebAppDeployment@5
        inputs:
          ConnectionType: 'AzureRM'
          appType: 'webApp'
          WebAppName: 'app-dsp-prototype'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
