trigger:
- develop
- feature/*
- jw-prototype-deploy-test

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '22.x'

steps:
  - task: UseNode@1
    inputs:
      version: $(nodeVersion)
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run dev
    displayName: 'Build project'

  - script: |
      npm test
    displayName: 'Run tests'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
        src/**
        public/**
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy project files'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'nodejs-app'
      targetPath: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish pipeline artifact'
