name: Build and deploy Node.js app to Azure Web App - prototypes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload root folder for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
          retention-days: 1  # Optional: keep artifact for 1 day

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./artifact

      - name: List downloaded files (debug)
        run: ls -R ./artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_723C35B463AB46AF8AA30A2B0D325A06 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FAB52441492545769732CA107A6A211C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5022F48012C3447FA99701F8287E86E9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prototypes'
          slot-name: 'Production'
          package: './artifact'
